import Navbar from './components/Navbar'; // <-- IMPORT IT
import './globals.css';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Navbar /> {/* <-- ADD IT HERE */}
                {children}
            </body>
        </html>
    );
}